### ISSUE TITLE
HAN FUN device Deutsche Telekom -> Error Log

### ISSUE THREAD

**Issue by matthias-zivim** [andig/homebridge-fritz#102]
Hallo und danke für dein Mühe. Ich habe ein HanFun Fenstersensor hinzugefügt und bekomme folgende Meldug im Log. Vielen Dank

Fritz 7590 7.12
HAN-FUN Sensor v31.35
Node.js Version v12.14.1
Npm Version v6.13.6
homebridge-fritz v0.9.2

Unhandled rejection ReferenceError: self is not defined
    at /homebridge/node_modules/homebridge-fritz/lib/accessories/alarmsensor.js:58:9
    at tryCatcher (/homebridge/node_modules/homebridge-fritz/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/homebridge/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/homebridge/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._fulfillPromises (/homebridge/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:704:14)
    at Promise._settlePromises (/homebridge/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:730:18)
    at _drainQueueStep (/homebridge/node_modules/homebridge-fritz/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/homebridge/node_modules/homebridge-fritz/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/homebridge/node_modules/homebridge-fritz/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/homebridge/node_modules/homebridge-fritz/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)

**Comment by matthias-zivim** [comment]
Fritz 7590 7.12
HAN-FUN Sensor v31.35
Node.js Version v12.14.1
Npm Version v6.13.6 
homebridge-fritz v0.9.2

**Comment by andig** [comment]
Schaue ich mir an, das sollte einfach zu lösen sein.

**Comment by andig** [comment]
Schau mal https://github.com/andig/homebridge-fritz/pull/111 - damit sollte es klappen?

**Comment by matthias-zivim** [comment]
homebridge-fritz v0.9.3

Unhandled rejection ReferenceError: self is not defined
    at FritzAlarmSensorAccessory.<anonymous> (/homebridge/node_modules/homebridge-fritz/lib/accessories/alarmsensor.js:58:9)
    at tryCatcher (/homebridge/node_modules/homebridge-fritz/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/homebridge/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/homebridge/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._fulfillPromises (/homebridge/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:704:14)
    at Promise._settlePromises (/homebridge/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:730:18)
    at _drainQueueStep (/homebridge/node_modules/homebridge-fritz/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/homebridge/node_modules/homebridge-fritz/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/homebridge/node_modules/homebridge-fritz/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/homebridge/node_modules/homebridge-fritz/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)

**Comment by andig** [comment]
Oh mann, natürlich. Moment!

**Comment by andig** [comment]
Erledigt. 0.9.4.

**Comment by matthias-zivim** [comment]
👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍

**Comment by matthias-zivim** [comment]
hab mal was gespendet :)

danke


Am 02.02.20 um 12:27 schrieb andig:
