### ISSUE TITLE
Fehlermeldung nach Start

### ISSUE THREAD

**Issue by michi692** [andig/homebridge-fritz#104]
Hallo,
ersteinmal möchte ich meinen Dank und Respekt für das tolle Plugin aussprechen. Ich nutze es nun seit einigen Tagen / Wochen und bin wirklich begeistert, meine DECT200er im Homekit bedienen zu können.

Nach dem Start der Homebridge erhalte ich diese Fehlermeldung, vielleicht kann hier jemand was mit anfangen:

```
Unhandled rejection ReferenceError: self is not defined
    at platform.fritz.then.devices (/usr/local/lib/node_modules/homebridge-fritz/lib/accessories/alarmsensor.js:58:9)
    at tryCatcher (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._fulfillPromises (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:704:14)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:730:18)
    at _drainQueueStep (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
```

Ist das ein Bug im Plugin oder eine falsche Konfig bei  mir?

Ich nutze die Homebridge mit einer Fritzbox 7590.

**Comment by andig** [comment]
Siehe #102
