### ISSUE TITLE
Plugin not working with Homebridge Version 1.0.0

### ISSUE THREAD

**Issue by MNieddu91** [andig/homebridge-fritz#121]
With the newest version of homebridge the plugin is not workig anymore. 

[4/27/2020, 8:52:54 AM] ERROR LOADING PLUGIN homebridge-fritz:
**[4/27/2020, 8:52:54 AM] Error: Plugin /homebridge/node_modules/homebridge-fritz requires a HomeBridge version of ^0.4.38 which does not satisfy the current HomeBridge version of 1.0.0. You may need to upgrade your installation of HomeBridge.**
    at Plugin.load (/usr/local/lib/node_modules/homebridge/src/plugin.ts:144:13)
    at /usr/local/lib/node_modules/homebridge/src/pluginManager.ts:119:16
    at Map.forEach (<anonymous>)
    at PluginManager.initializeInstalledPlugins (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:117:18)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:148:24)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:74:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)

**Comment by f-io** [comment]
docker-compose exec hombridge sh
nano /homebridge/node_modules/homebridge-fritz/package.json 

###
"engines": {
 --    "homebridge": "^0.4.8",
 ++   "homebridge": "^1.0.0",
    "node": ">4.0.0"
  },
##

**Comment by andig** [comment]
Would appreciate a PR.

**Comment by f-io** [comment]
already done.

**Comment by MNieddu91** [comment]
Thanks for quick response.

**Comment by MNieddu91** [comment]
Sorry das ich den issue wieder aufmachen muss.
Mit dem editieren der package.json funktionierte Homebridge auf v1.0.0 mit homebride-fritz 0.9.4 wieder einwandfrei. 
Nun habe ich das Update auf 0.9.5 durchgeführt und bekomme einen neuen Fehler:
[4/27/2020, 12:36:53 PM] Error loading platform requested in your config.json at position 1
[4/27/2020, 12:36:54 PM] Error: The requested platform 'Fritz!Box' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:223:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:361:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:348:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:151:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:74:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

**Comment by andig** [comment]
Probably due to https://github.com/andig/homebridge-fritz/pull/120. Could you update to `FRITZ!Box` (casing)? If that works I'll make the issue more transparent here.

**Comment by MNieddu91** [comment]
Yes, thats it.
Platform has to be "platform": "**FRITZ**!Box"

Thanks a lot.

**Comment by andig** [comment]
See https://github.com/andig/homebridge-fritz/issues/124

**Comment by f-io** [comment]
Kann ich nicht bestätigen, "platform": "Fritz!Box" läuft bei mir. Ich werde das auch nicht großschreiben, da ich das ja auch nicht schreie wenn ich es lese.

**Comment by f-io** [comment]
jetzt muss ich immer schreien wenn ich das lese :(
