### ISSUE TITLE
[EN] No Login possible - [DE] Kein Login Möglich 

### ISSUE THREAD

**Issue by DerPicknicker** [andig/homebridge-fritz#129]
[EN]

Hi,

No Login possible, I make a new FB Account only for Smarthome and homebridge to be on the safe side... The Password is correct but the Plugin said : Initializing FRITZ!Box platform accessories failed - wrong user credentials? ... 

[/EN]

[DE]
Hallo, 

Das Plugin wurde in Homebridge installiert und wird auch erkannt es ist keine Anmeldung mit neuem Benutzer auf der Fritzbox möglich. Ich habe einen neuen erstellt, damit ich immer auf der Sicheren Seite bin. Deshalb weiß ich zu 100% das die Login Daten stimmen. Ich weiß nicht was ich noch tun kann. Wenn du weitere Infos benötigst, dann sag bescheid.

**Comment by andig** [comment]
Can you login if the account gets further rights?

**Comment by DerPicknicker** [comment]
No, that won't work either. I can't log in. 

I initially limited the permissions to the Smarthome. Then I gave him the permissions for the Fritzbox settings. Does not work either.

**Comment by andig** [comment]
> No, that won't work either. I can't log in.

Did it ever work before? What has changed since? Do you have special characters in username or password?

**Comment by appliko** [comment]
Anything on fritz log ?

**Comment by DerPicknicker** [comment]
> > No, that won't work either. I can't log in.
> 
> Did it ever work before? What has changed since? Do you have special characters in username or password?

No, simple Username „HomeKit“ & Password something like this : „12wmX345GJK“ ... I didn’t change anything it won’t work. I installed the plugin and edit my config but Homebridge can’t load FritzBox items because the plugin fails to login.. 




> Anything on fritz log ?
> […](#)

No nothing in the log... No Login attempts...

**Comment by BionicThomas** [comment]
Would try it with the default admin user first to rule out any other issue.
...
"username": "admin",
 "password": "your admin password",
...

**Comment by DerPicknicker** [comment]
I can now connect to the FritzBox but I get new errors... 

.....
[5/4/2020, 09:47:30] [My FRITZ!Box] Updating guest WLAN
[5/4/2020, 09:47:30] [My FRITZ!Box] 401: Unauthorized
[5/4/2020, 09:47:33] [My FRITZ!Box] Updating outlet AIN
[5/4/2020, 09:48:30] [My FRITZ!Box] Updating guest WLAN
[5/4/2020, 09:48:30] [My FRITZ!Box] 401: Unauthorized
[5/4/2020, 09:48:33] [My FRITZ!Box] Updating outlet AIN
.....

The Logs from the FritzBox says now : Registration of an app with unknown login name from IP address 192.xxx.xxx.xx

Is it possible to use the temp Sensor as actor? I would like to set an socket on or off based on the temp...

**Comment by user858753257** [comment]
Same issue here . I have installed the plugin in Hoobs 3.2.2 with Node 10.18.0

Following error messages i see in the log file : 

```
.5.2020, 11:12:05 Error: The requested platform "Fritz!Box" was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/api.js:128:23)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:271:35)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:87:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
4.5.2020, 11:12:05 Got SIGTERM, shutting down Bridge...
```

**Comment by andig** [comment]
That is a different problem, your solution is in https://github.com/andig/homebridge-fritz/issues/124

**Comment by DerPicknicker** [comment]
An additional information : 
I don’t need an username for login (Homenetwork) I need only usernames for the User Login (SmartHome, NAS..) Other Smarthomeskills for Alexa work with these structure..

**Comment by DerPicknicker** [comment]
@andig 
Okay I could get more information about the problem. It is a issue from the Plugin itself. 
If in the FRITZ!Box Login without username is enabled the Username should be blank in the config.json... 

But the main thing is that THIS Plugin doesn’t support other FRITZ!Box User. No other User is usable for this plugin. This is quite bad because I don’t want to have one user for all. I would like to have one for the Alexa integration, one for HomeKit ... 
No other User could Sign in - It ends with this Error :  Initializing FRITZ!Box platform accessories failed - wrong user credentials? ...

But without Username I get other ERRORS but the Things are visible in the Home App and they work fine..

**Comment by andig** [comment]
> If in the FRITZ!Box Login without username is enabled the Username should be blank in the config.json.

The smart home api needs a session and to get that you need to login. 

> But the main thing is that THIS Plugin doesn’t support other FRITZ!Box User. No other User is usable for this plugin.

I don‘t follow. Feel free to switch to German if that would be easier?

**Comment by DerPicknicker** [comment]
> > But the main thing is that THIS Plugin doesn’t support other FRITZ!Box User. No other User is usable for this plugin.
> 
> I don‘t follow. Feel free to switch to German if that would be easier?

Short Answer : The FRTIZ!Box User won’t work. I don’t need a Username for the Login to the WEBUI of the FB.. But I have different user for different Tasks..
If I use the Password for the Username „HomeKit“ it won’t work. 
If I don’t use any username and the Password of the WEBUI it works.

**Comment by olivermast** [comment]
Same problem here until two days: Initializing FRITZ!Box platform accessories failed - wrong user credentials?

No settings changed, User: admin Pass: 1234…

Never Problems before.

I try user "admin", "root" and "" no changes.
