### ISSUE TITLE
error not registered pluginn

### ISSUE THREAD

**Issue by antagosteenl** [andig/homebridge-fritz#144]
Hi am getting this error after installing the plugin.

Error: The requested platform 'Fritz!Box' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:387:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

**Comment by andig** [comment]
See https://github.com/andig/homebridge-fritz/issues/124
