### ISSUE TITLE
fehler beim anpassen der Config.json

### ISSUE THREAD

**Issue by stpusch** [andig/homebridge-fritz#21]
Hallo,

ich bekomme immer folgende Fehlermeldung wenn ich die Konfigurationsdatei erstelle.
Was mache ich Falsch?

Viele Dank schonmal für die Hilfe :)

hier mal ein Auszug 

[2017-02-21 00:11:24] Loaded plugin: homebridge-fritz
[2017-02-21 00:11:24] Registering platform 'homebridge-fritz.Fritz!Box'
[2017-02-21 00:11:24] ---
[2017-02-21 00:11:24] config.json (/home/pusch/.homebridge/config.json) not found.
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-15x │     
    └────────────┘     
                       
[2017-02-21 00:11:24] Homebridge is running on port 46558.

Loaded plugin: homebridge-fritz
[2017-02-21 00:14:52] Registering platform 'homebridge-fritz.Fritz!Box'
[2017-02-21 00:14:52] ---
/usr/local/lib/node_modules/homebridge/lib/server.js:202
  var username = config.bridge.username;
                              ^

TypeError: Cannot read property 'username' of undefined
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:202:31)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:52:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by andig** [comment]
Deiner homebridge Installation scheint die Konfigurationsdatei zubfrhlen.

**Comment by stpusch** [comment]
Vielen Dank für die schnelle Antwort

ich bin gerade echt am verzweifeln...

sobald ich die config.json erstelle bekomm ich folgende Fehlermeldung

[2017-02-21 12:44:56] There was a problem reading your config.json file.
[2017-02-21 12:44:56] Please try pasting your config.json file here to validate it: http://jsonlint.com

Ich hab die  config schon validieren lassen und da wir mir kein fehler angezeigt...

Haben sie noch einen Tipp für mich ?
Vielen Dank !!!

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"accessories": [],

	"platforms": [{
		"platform": "Fritz!Box",
		"name": "My FritzBox",
		"username": "pusch",
		"password": "12345678",
		"url": "http://fritz.box",
		"interval": 60,
		"options": {
			"strictSSL": false
		}
	}]


	 
}

**Comment by andig** [comment]
Die sieht eigentlich richtig aus. Evtl. falsche Zeilenendungen weil auf
Windows PC bearbeitet statt under Linux?
