### ISSUE TITLE
Failure during running fritz plugin and hanging up homebridge

### ISSUE THREAD

**Issue by Tobitobsen81** [andig/homebridge-fritz#24]
after starting homebridge with fritz plugin (both latest versions) i get a failure when i open home app on iPhone. the raspberry pi will write the following log. the system is running after this log but will hang up the system after a while mostly one or two hours after restart.

LOG:
6/25/2017, 2:29:21 PM > Unhandled rejection Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
    at /usr/local/lib/node_modules/homebridge-fritz/index.js:501:13
    at tryCatcher (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._fulfillPromises (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:668:14)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:694:18)
    at Async._drainQueue (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by andig** [comment]
What is the latest working version?

**Comment by Tobitobsen81** [comment]
the problem occurred with version 0.5.4 and version 0.5.5 was the same problem. i use 2 Fritz!DECT (300) and Comet!DECT thermostats

**Comment by andig** [comment]
Should be fixed in 0.5.6- thanks for spotting this one!

**Comment by Tobitobsen81** [comment]
Thanks, your fix is working. i give you the next weeks feedback if it is stable now.
