### ISSUE TITLE
Seems not to work

### ISSUE THREAD

**Issue by abataille** [andig/homebridge-fritz#3]
I just did a test and received the following issue:

[2016-08-02 15:50:28] [My FritzBox] Initializing platform accessory ''...
Unhandled rejection Error: Accessories must be created with a non-empty displayName.
    at new Accessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:46:27)
    at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:375:21)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:343:32)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at /usr/local/lib/node_modules/homebridge-fritz/index.js:87:21
    at tryCatcher (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate](/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback](timers.js:383:17)

**Comment by andig** [comment]
Could you set debug=true in the plugin options and post the output?

**Comment by abataille** [comment]
Will so tomorrow.
There seems to be something wrong in the index.js. When I comment out the switch and temperature at line 67 ff the issues will not come up. 
Doing this I can activate the guest wlan, but I cannot deactivate it.

**Comment by abataille** [comment]
I suggest the following changes to index.js (line 58 - 92). Some bracketing look strange. I tried and it works fine.
 accessories: function(callback) {
        this.log("Discovering accessories");

```
    var accessories = [];
    var self = this;

    // wifi
    accessories.push(new FritzWifiAccessory(this));

    this.fritz("getDeviceList").then(function(devices) {
        // cache list of devices in options for reuse by non-API functions
        self.options.deviceList = devices;

        // outlets
        self.fritz("getSwitchList").then(function(ains) {
            self.log("Outlets found: %s", ains.toString());

            ains.forEach(function(ain) {
                accessories.push(new FritzOutletAccessory(self, ain));
            });
            });
            // thermostats
            self.fritz('getThermostatList').then(function(ains) {
                self.log("Thermostats found: %s", ains.toString());

                ains.forEach(function(ain) {
                    accessories.push(new FritzThermostatAccessory(self, ain));
                });


            });
       callback(accessories);
    });

},
```

**Comment by andig** [comment]
> I suggest the following changes to index.js (line 58 - 92). Some bracketing look strange. I tried and it works fine.

Nothing strange about those. Its just that the calls should be sequential or the callback will be premature and incomplete. 

Could you please set debug=true in the plugin config and post the logfile when you start homebridge?

> Doing this I can activate the guest wlan, but I cannot deactivate it.

This sounds like a problem with the smartfritz-promise library. Could you please open an issue at https://github.com/andig/smartfritz including your FB model and version?

**Comment by abataille** [comment]
There is no other log file. Any idea about  its location?

**Comment by andig** [comment]
Stop the service and start homebridge on the command line:

```
DEBUG=* homebrige
```

and post the output.

**Comment by abataille** [comment]
[8/5/2016, 7:30:37 AM] Loaded plugin: homebridge-fritz
[8/5/2016, 7:30:38 AM] Registering platform 'homebridge-fritz.Fritz!Box'
[8/5/2016, 7:30:38 AM] ---
[8/5/2016, 7:30:38 AM] Loaded config.json with 0 accessories and 1 platforms.
[8/5/2016, 7:30:38 AM] ---
[8/5/2016, 7:30:39 AM] Loading 1 platforms...
[8/5/2016, 7:30:39 AM] [FB7490] Initializing Fritz!Box platform...
[8/5/2016, 7:30:39 AM] [FB7490] Discovering accessories
[8/5/2016, 7:30:39 AM] Loading 0 accessories...
[8/5/2016, 7:30:41 AM] [FB7490] Fritz!Box platform login successful
[8/5/2016, 7:30:41 AM] [FB7490] Outlets found: 
[8/5/2016, 7:30:41 AM] [FB7490] Thermostats found: 
[8/5/2016, 7:30:41 AM] [FB7490] Initializing platform accessory 'Guest WLAN'...
[8/5/2016, 7:30:42 AM] [FB7490] Initializing platform accessory ''...
Unhandled rejection Error: Accessories must be created with a non-empty displayName.
    at new Accessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:46:27)
    at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:375:21)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:343:32)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at /usr/local/lib/node_modules/homebridge-fritz/index.js:87:21
    at tryCatcher (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._fulfillPromises (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:660:14)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:686:18)
    at Async._drainQueue (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate](/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback](timers.js:371:17)

[8/5/2016, 7:31:39 AM] [FB7490] Updating guest WLAN
[8/5/2016, 7:31:41 AM] [FB7490] Updating outlet

**Comment by andig** [comment]
I can see what happens but dont understand why. Is there any remote chance you could pm me http login for your fritz box? I'd need to play with it, teamviewer session would also work.

**Comment by abataille** [comment]
Unfortunately I can’t do that.
It is FB 7490 with OS 6.60.
I made a temporary change to your index.js, just to use the Guest WLAN switch, because I do not have the other accessories yet.
Thank you.

**Comment by andig** [comment]
> I made a temporary change to your index.js, just to use the Guest WLAN switch, because I do not have the other accessories yet.

It should still work.

> Unfortunately I can’t do that.

Too bad. No fixing I can do without further insights. 

Would you be able to run some sample code directly against smartfritz (only makes sense if you're somewhat comfortable with programming).

**Comment by abataille** [comment]
I can try.

**Comment by andig** [comment]
ok, then please run this from the folder where smartfritz-promise is already insalled (usually something like `homebridge-fritz/node_modules/smartfritz`) using node:

```
var fritz = require('./smartfritz.js');

var options = {
    // "url": URL
};

var username = "username";
var password = "password";


fritz.getSessionID(username, password, options).then(function(sid) {
    console.log("SID: " + sid);

    fritz.getSwitchList(sid, options).then(function(switches) {
        console.log("Switches: ");
        console.log(JSON.stringify(switches));

        fritz.getThermostatList(sid, options).then(function(thermostats) {
            console.log("Thermostats: ");
            console.log(JSON.stringify(thermostats));
        });
    });
})
.catch(function(error) {
    console.error(error);
});
```

**Comment by abataille** [comment]
It results into
SID: 8090ac00cfdd5972
Switches: 
[""]
Thermostats: 
[]

So, the empty string in Switches is the problem.

**Comment by andig** [comment]
> [""]

Interesting. Could you also hack the library itself and before this line: https://github.com/andig/smartfritz/blob/master/smartfritz.js#L237 insert an:

```
console.log(JSON.stringify(res));
```

Might be a Fritz API bug or my JS needs updating ;)

Darn. My JS needs updating: http://stackoverflow.com/questions/5164883/the-confusion-about-the-split-function-of-javascript

I'll fix this right away.

**Comment by andig** [comment]
Could you check if it works with this return line:

```
    return Promise.resolve(res === "" ? [] : res.split(','));
```

**Comment by abataille** [comment]
will try.

**Comment by abataille** [comment]
This works !! Thanks

**Comment by andig** [comment]
Fixed via https://github.com/andig/homebridge-fritz/commit/3b82c70420137273f985679e30d2a331ee390e2f 

Please upgrade to 0.2.4
