### ISSUE TITLE
Fakegato-history support

### ISSUE THREAD

**Issue by mathiaswagner** [andig/homebridge-fritz#52]
Not sure how much effort that is, but having the history esp for the temperature sensors in the DECT outlets and the DECT thermostats seems to be useful.

https://github.com/simont77/fakegato-history

**Comment by andig** [comment]
I'll keep this open as an enhancement but have not personal use for it at this time. I'm using https://volkszaehler.org for all my monitoring needs.

**Comment by mathiaswagner** [comment]
Seems like @thncode has some initial support. Not sure if this is ready for integration. 

https://github.com/thncode/homebridge-fritz

**Comment by cschildhorn** [comment]
This feature would be nice. Temperature history in the Eve app is really good. Mentioned that after using homebridge-eveatmo plugin that tries to mimik eve sensor for creating history data for netatmo stuff.

**Comment by Phoenix-DH** [comment]
+1

**Comment by andig** [comment]
I would be ahopy to accept a PR. My preferred to for monitoring is https://volkszaehler.org

**Comment by thncode** [comment]
my fork works great for me meanwhile - would be nice if this would be integrated...

**Comment by andig** [comment]
@thncode This is open software and open software thrives on contributions and sharing workload. As I wrote above- I'd be happy to accept a pr. It would also be great if you could check #56.

**Comment by Phoenix-DH** [comment]
@thncode:
Yes, would be great ... I ha issue with your fork mentioned in https://github.com/andig/homebridge-fritz/issues/56

Thanks.

Or how do I have to install your fork? I did it that way:
npm install -g --unsafe-perm https://github.com/thncode/homebridge-fritz

Then there was the message that there is an update from version 0.7.3 to version 0.7.5

0.7.3 was working, but there was no temperature sensor available at all ...
With version 0.7.5 it crashes.

**Comment by thncode** [comment]
@Phoenix-DH how does 0.7.6 work?

**Comment by Phoenix-DH** [comment]
@thncode Now homebridge is running, but the temperature icon in homekit disappears.

I got the following in the log:
```
[2018-12-21 10:13:30] [Phoenix FritzBox] Alarm sensors found: none
[2018-12-21 10:13:30] [Phoenix FritzBox] Outlets found: 087610136610
HAP Warning: Characteristic E863F10D-079E-48FF-8F27-9C2605A29F52 not in required or optional characteristics for service 00000047-0000-1000-8000-0026BB765291. Adding anyway.
HAP Warning: Characteristic E863F10C-079E-48FF-8F27-9C2605A29F52 not in required or optional characteristics for service 00000047-0000-1000-8000-0026BB765291. Adding anyway.
HAP Warning: Characteristic 00000011-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000047-0000-1000-8000-0026BB765291. Adding anyway.
```

**Comment by carsten-h** [comment]
Hello!

I am getting these messages when I try to set a temperature of a COMET DECT device:

`[1/25/2019, 9:02:25 PM] [My FritzBox] Getting temperature sensor 116570001689 temperature
homebridge : TTY=pts/0 ; PWD=/var/homebridge ; USER=root ; COMMAND=/bin/journalctl -o cat -n 500 -f -u homebridge
pam_unix(sudo:session): session opened for user root by (uid=0)
Unhandled rejection ReferenceError: fritz is not defined
    at /usr/local/lib/node_modules/homebridge-fritz-eve/lib/accessories/thermostat.js:153:9
    at tryCatcher (/usr/local/lib/node_modules/homebridge-fritz-eve/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-fritz-eve/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-fritz-eve/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-fritz-eve/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-fritz-eve/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/usr/local/lib/node_modules/homebridge-fritz-eve/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/local/lib/node_modules/homebridge-fritz-eve/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-fritz-eve/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-fritz-eve/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (timers.js:632:19)`

**Comment by Phoenix-DH** [comment]
> @thncode Now homebridge is running, but the temperature icon in homekit disappears.
> 
> I got the following in the log:
> 
> ```
> [2018-12-21 10:13:30] [Phoenix FritzBox] Alarm sensors found: none
> [2018-12-21 10:13:30] [Phoenix FritzBox] Outlets found: 087610136610
> HAP Warning: Characteristic E863F10D-079E-48FF-8F27-9C2605A29F52 not in required or optional characteristics for service 00000047-0000-1000-8000-0026BB765291. Adding anyway.
> HAP Warning: Characteristic E863F10C-079E-48FF-8F27-9C2605A29F52 not in required or optional characteristics for service 00000047-0000-1000-8000-0026BB765291. Adding anyway.
> HAP Warning: Characteristic 00000011-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000047-0000-1000-8000-0026BB765291. Adding anyway.
> ```

Forget nto comming back to this topic.
I tried again after my Fritz!Box has been updated to 7.01.
It is still the same behaviour:
THe extra temp switch has gone, but the one inside the Rack in Eve is visible and seems to be working for the actual temperature.
But history is not working ... all history values are 0° .. atual value fine.
![IMG_4172](https://user-images.githubusercontent.com/44058592/55864773-6bda0280-5b7d-11e9-9552-3382c63a0460.PNG)

And those alerts I also still got.

Thanks for the support.

**Comment by andig** [comment]
> my fork works great for me meanwhile - would be nice if this would be integrated...

ping @thncode if this is something you want to contribute please open a PR
