### ISSUE TITLE
Problem with thncode fork - homebridge wont start

### ISSUE THREAD

**Issue by Phoenix-DH** [andig/homebridge-fritz#56]
Hi,

when I use the fork of thncode with the eve extension I get the following error when homebridge starts:
```
[2018-12-13 19:20:36] [Phoenix FritzBox] Outlets found: 087610136610
Unhandled rejection ReferenceError: services is not defined
    at new FritzOutletAccessory (/usr/lib/node_modules/homebridge-fritz-eve/lib/accessories/outlet.js:68:5)
    at /usr/lib/node_modules/homebridge-fritz-eve/lib/platform.js:130:46
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge-fritz-eve/lib/platform.js:128:26
    at tryCatcher (/usr/lib/node_modules/homebridge-fritz-eve/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-fritz-eve/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-fritz-eve/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._fulfillPromises (/usr/lib/node_modules/homebridge-fritz-eve/node_modules/bluebird/js/release/promise.js:669:14)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-fritz-eve/node_modules/bluebird/js/release/promise.js:695:18)
    at _drainQueueStep (/usr/lib/node_modules/homebridge-fritz-eve/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/lib/node_modules/homebridge-fritz-eve/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/lib/node_modules/homebridge-fritz-eve/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/homebridge-fritz-eve/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

Can someone give me a hint?

**Comment by andig** [comment]
What do you mean by thncode fork?

**Comment by Phoenix-DH** [comment]
I mean this one here:
https://github.com/thncode/homebridge-fritz

I want to have eve history included and read that this fork should have it already implemented.
But I got the message obove.

There is no possibility to add issues on this fork directly.

**Comment by andig** [comment]
Can you reproduce with this fork? If not I‘ll have to close it.

**Comment by Phoenix-DH** [comment]
NO I can't, I have your fork in use, everything fine.
I go this way because this is the only possibility to have a conversation on this topic.
