### ISSUE TITLE
Steuerungsbefehle

### ISSUE THREAD

**Issue by g60driveer** [andig/homebridge-fritz#66]
Hallo! Ich habe die Version 0.8.0 - die Geräte werden auch im Home erkannt.
Jedoch benötige für weitergehende Nutzung die Info wie ich die Befehle zur Ansteuerung der DECT301 nutzen kann.

Ich habe beispielsweise probiert mit:
node homebridge-fritz "ain=(AIN DES DECT GERÄT)&switchcmd=getTemperature"

bekomme jedoch folgende Fehlermeldung:
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '/home/pi/homebridge-fritz'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

was mache ich da falsch?

**Comment by andig** [comment]
> node homebridge-fritz "ain=(AIN DES DECT GERÄT)&switchcmd=getTemperature"

Du scheinst das als Kommandozeilenapplikation auszuführen? Dafür ist es nicht gedacht sondern als Homebridge Plugin.

**Comment by andig** [comment]
Closing due to inactivity.
