### ISSUE TITLE
Cannot read property 'manufacturer' of undefined

### ISSUE THREAD

**Issue by rogiervandergeer** [andig/homebridge-fritz#8]
When trying to use this plugin with my Fritz!Box I'm getting the following error:

```
[10/5/2016, 7:25:55 AM] Loaded plugin: homebridge-fritz
[10/5/2016, 7:25:55 AM] Registering platform 'homebridge-fritz.Fritz!Box'
[10/5/2016, 7:25:55 AM] ---
[10/5/2016, 7:25:55 AM] Loaded config.json with 0 accessories and 1 platforms.
[10/5/2016, 7:25:55 AM] ---
[10/5/2016, 7:25:55 AM] Loading 1 platforms...
[10/5/2016, 7:25:55 AM] [My FritzBox] Initializing Fritz!Box platform...
[10/5/2016, 7:25:55 AM] [My FritzBox] Discovering accessories
[10/5/2016, 7:25:56 AM] [My FritzBox] Fritz!Box platform login successful
[10/5/2016, 7:25:57 AM] [My FritzBox] Outlets found: 087610162179,087610164200,C2:B6:94-900
Unhandled rejection TypeError: Cannot read property 'manufacturer' of undefined
    at FritzOutletAccessory.FritzAccessory (/usr/lib/node_modules/homebridge-fritz/index.js:235:72)
    at new FritzOutletAccessory (/usr/lib/node_modules/homebridge-fritz/index.js:254:20)
    at /usr/lib/node_modules/homebridge-fritz/index.js:92:38
    at Array.forEach (native)
    at /usr/lib/node_modules/homebridge-fritz/index.js:91:22
    at tryCatcher (/usr/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/usr/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/usr/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

While it reports to have found three outlets, I only have two. I assume the third outlet would be the group I created, that contains both the real outlets. I guess it cannot read the name and manufacturer of the group.

**Comment by andig** [comment]
Interesting. I've not seen "groups" before. Is that a new functionality? Could you share a screenshot of the group definition?

**Comment by rogiervandergeer** [comment]
Here you go. Inside the configuration ("Smart Home Profile") of an outlet there is a "Group Switching" option: 
<img width="773" alt="screen shot 2016-10-05 at 14 31 14" src="https://cloud.githubusercontent.com/assets/11784324/19113159/a69dacb6-8b08-11e6-9290-b37cbcd00cbf.png">

Once set up it looks like this in the overview:
<img width="784" alt="screen shot 2016-10-05 at 14 30 42" src="https://cloud.githubusercontent.com/assets/11784324/19113158/a69a562e-8b08-11e6-9fc1-a98d778a1ca7.png">

I don't think it's such a new feature: I've been using it for about a year now.

**Comment by andig** [comment]
Thanks. I assume you also want the ability to seitch groups? I'll need to check exact behaviour in my local install.

**Comment by rogiervandergeer** [comment]
Ideally, yes. But of course we can recreate a group in HomeKit using a scene. 

Let me know how I can help.

**Comment by andig** [comment]
As I'm traveling- any chance to post an output of GetDeviceList for your setup?

**Comment by rogiervandergeer** [comment]
I think this is what you need? As you see the device three looks like a normal device but has no temperature.

`{u'DeviceID_2': u'17', u'DeviceConnectState_2': u'2', u'DeviceID_1': u'16', u'DeviceSwitchLock_1': u'0', u'DeviceSwitchLock_2': u'0', u'DeviceID_3': u'900', u'DeviceSwitchState_3': u'1', u'DeviceSwitchState_2': u'1', u'DeviceSwitchState_1': u'1', u'DeviceSwitchLock_3': u'0', u'DeviceTemp_1': u'223', u'DeviceConnectState_3': u'2', u'DeviceTemp_3': u'', u'DeviceConnectState_1': u'2', u'RequestResult': u'1', u'DeviceTemp_2': u'231', u'Outlet_count': u'3'}`

**Comment by andig** [comment]
That's not quite what I was looking for. See here- the group is returned as switch device but doesn't seem to exist in the device list at all:

```
Switches: 087610103568,AA:85:6A-900
Devices:
[
  {
    "identifier": "08761 0103568",
    "id": "16",
    "functionbitmask": "896",
    "fwversion": "03.59",
    "manufacturer": "AVM",
    "productname": "FRITZ!DECT 200",
    "present": "1",
    "name": "FRITZ!DECT 200 #1",
    "switch": {
      "state": "1",
      "mode": "manuell",
      "lock": "0"
    },
    "powermeter": {
      "power": "0",
      "energy": "642567"
    },
    "temperature": {
      "celsius": "195",
      "offset": "0"
    }
  }
]
```

Can you repro with this code?

```
fritz.getSessionID(username, password, options).then(function(sid) {
    console.log("SID: " + sid);

    // display switch information
    fritz.getSwitchList(sid, options).then(function(switches) {
        console.log("Switches: " + switches);

        fritz.getDeviceList(sid, options).then(function(devices) {
            console.log("Devices: \n" + JSON.stringify(devices, null, 2));
        });
    });
});
```

**Comment by andig** [comment]
Ok. Could you check if this works for you (update the index.js file of the homebridge-fritz module):

```
/**
 * FritzAccessory
 */

function FritzAccessory(platform, ain) {
    this.platform = platform;
    this.ain = ain;
    this.name = this.platform.getName(this.ain);
    this.device = this.platform.getDevice(this.ain);

    this.services = {
        AccessoryInformation: new Service.AccessoryInformation()
            .setCharacteristic(Characteristic.SerialNumber, this.ain)
    };

    if (this.device) {
        this.services.AccessoryInformation
            .setCharacteristic(Characteristic.Manufacturer, this.device.manufacturer)
            .setCharacteristic(Characteristic.Model, this.device.productname)
            .setCharacteristic(Characteristic.FirmwareRevision, this.device.fwversion)
    }
};
```

**Comment by rogiervandergeer** [comment]
Thanks! That didn't fix it but pushed me in the right direction. The problem lies in `index.js` on line 279. There `this.device` is undefined, hence `this.device.temperature` gives the problem. This, together with your change above, does seem to fix it:

```
    if (this.device) {
        if (this.device.temperature) {
            extend(this.services, {
                TemperatureSensor: new Service.TemperatureSensor(this.name)
            });

            this.services.TemperatureSensor.getCharacteristic(Characteristic.CurrentTemperature)
                .on('get', this.getCurrentTemperature.bind(this))
                ;
        };
    };
```

I'm not at home right now so I cannot test the functionality, but homebridge does start and discover the outlets without problems. I'll test when I can and let you know.

**Comment by andig** [comment]
I'll provide a PR for your issue together with https://github.com/andig/homebridge-fritz/issues/7 asap

**Comment by andig** [comment]
Please test https://github.com/andig/homebridge-fritz/pull/9

**Comment by rogiervandergeer** [comment]
That didn't do it, unfortunately. As the `device` is undefined for the group, I get errors at lines 254, 258, 262 and 305. I can circumvent this by adding `if (self.device) { }` around these cases.

_However_, then I still get errors. So I made sure that at line 92 the group isn't added to the list;

```
ains.forEach(function(ain) {
       var new_accessory = new FritzOutletAccessory(self, ain);
       if (new_accessory.device) {
           self.log("Adding: %s", ain.toString());
           accessories.push(new_accessory);
       }
});
```

and checked it now indeed is not added. Then I still see the following errors in the log:

```
[10/10/2016, 6:12:58 PM] [My FritzBox] > getTemperature failed - retrying in 3 seconds
[10/10/2016, 6:12:58 PM] [My FritzBox] { error: null,
  response:
   IncomingMessage {
     _readableState:
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _events:
      { end: [Object],
        close: [Object],
        data: [Function],
        error: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     socket:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'fritz.box',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        _bytesDispatched: 151,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     connection:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'fritz.box',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        _bytesDispatched: 151,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers:
      { connection: 'close',
        'content-length': '0',
        'content-type': 'text/plain; charset=utf-8' },
     rawHeaders:
      [ 'Connection',
        'close',
        'Content-Length',
        '0',
        'Content-Type',
        'text/plain; charset=utf-8' ],
     trailers: {},
     rawTrailers: [],
     upgrade: false,
     url: '',
     method: null,
     statusCode: 400,
     statusMessage: 'Bad Request',
     client:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'fritz.box',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        _bytesDispatched: 151,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     _consuming: true,
     _dumped: false,
     req:
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedHeader: {},
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET /webservices/homeautoswitch.lua?0=0&sid=637b2fc064d368a0&switchcmd=gettemperature&ain=087610162179 HTTP/1.1\r\nhost: fritz.box\r\nConnection: close\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        method: 'GET',
        path: '/webservices/homeautoswitch.lua?0=0&sid=637b2fc064d368a0&switchcmd=gettemperature&ain=087610162179',
        _ended: true,
        parser: null,
        res: [Circular] },
     request:
      Request {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        strictSSL: false,
        deviceList: [Object],
        callback: [Function],
        readable: true,
        writable: true,
        _qs: [Object],
        _auth: [Object],
        _oauth: [Object],
        _multipart: [Object],
        _redirect: [Object],
        _tunnel: [Object],
        headers: {},
        setHeader: [Function],
        hasHeader: [Function],
        getHeader: [Function],
        removeHeader: [Function],
        method: 'GET',
        localAddress: undefined,
        pool: [Object],
        dests: [],
        __isRequestRequest: true,
        _callback: [Function],
        uri: [Object],
        rejectUnauthorized: false,
        proxy: null,
        tunnel: false,
        setHost: true,
        originalCookieHeader: undefined,
        _disableCookies: true,
        _jar: undefined,
        port: 80,
        host: 'fritz.box',
        path: '/webservices/homeautoswitch.lua?0=0&sid=637b2fc064d368a0&switchcmd=gettemperature&ain=087610162179',
        httpModule: [Object],
        agentClass: [Object],
        agent: [Object],
        _started: true,
        href: 'http://fritz.box/webservices/homeautoswitch.lua?0=0&sid=637b2fc064d368a0&switchcmd=gettemperature&ain=087610162179',
        req: [Object],
        ntick: true,
        response: [Circular],
        originalHost: 'fritz.box',
        originalHostHeaderName: 'host',
        responseContent: [Circular],
        _ended: true,
        _callbackCalled: true },
     toJSON: [Function: responseToJSON],
     caseless: Caseless { dict: [Object] },
     read: [Function],
     body: '' },
  options:
   { url: 'http://fritz.box/webservices/homeautoswitch.lua?0=0&sid=637b2fc064d368a0&switchcmd=gettemperature&ain=087610162179',
     deviceList: [ [Object], [Object] ] } }
```

The device ain referenced here is _not_ the group. Is this related? Did I break something? Or is it something else entirely?

**Comment by andig** [comment]
> That didn't do it, unfortunately. As the device is undefined for the group, I get errors at lines 254, 258, 262 and 305. I can circumvent this by adding if (self.device) { } around these cases.

Stupid oversight on my side. Cannot really test right now so this crept in. Will update.

> However, then I still get errors. So I made sure that at line 92 the group isn't added to the list;

Could you be specific what those are if you leave the group in?

**Comment by andig** [comment]
Ok, guess I found it. PR is updated.

**Comment by rogiervandergeer** [comment]
It appears that the `this.options.deviceList.find` returns undefined for the group. I can fix it like this:

```
    getDevice: function(ain) {
        if (this.options.deviceList) {
            var device = this.options.deviceList.find(function(device) {
                return device.identifier.replace(/\s/g, '') == ain;
            });
            if (device) {
                return device;
            }
            return {};
        }
        return {}; // safeguard
    },
```

Then I still get the `getTemperature failed` errors. Are these related?

**Comment by andig** [comment]
> It appears that the this.options.deviceList.find returns undefined for the group.

Good catch. That's the downside when coding without testing. I've updated the PR.

> Then I still get the getTemperature failed errors. Are these related?

Can you confirm that you're on the code basis of the PR, especially https://github.com/andig/homebridge-fritz/pull/9/files#diff-168726dbe96b3ce427e7fedce31bb0bcR302? Then this shouldn't happen.

As we don't have any other logging we need to find which ain causes this. Please change any `getTemperature` like this:

```
var self = this;
this.platform.fritz('getTemperature', this.ain).then(function(temp) {
    callback(null, temp);
}).catch(function(error) {
    console.error('AIN: ' + ain);
    console.error(error);
});
```

Update all calls until you find the culprit. We need to understand which AIN is causing this. Function should not be called for groups.

**Comment by andig** [comment]
You could also set `debug=true` in the config to get additional logging- please see if that gives better insight and provide a full logfile with the current PR code.

**Comment by rogiervandergeer** [comment]
I no longer have any problems with `device` being undefined, thanks! Now remains the `getTemperature` issue. I tracked it down to line 383. The catch doesn't work, as the catch in line 162 always handles the error. Here is the full log:

```
[10/12/2016, 1:30:29 PM] Loaded plugin: homebridge-fritz
[10/12/2016, 1:30:29 PM] Registering platform 'homebridge-fritz.Fritz!Box'
[10/12/2016, 1:30:29 PM] ---
[10/12/2016, 1:30:29 PM] Loaded config.json with 0 accessories and 1 platforms.
[10/12/2016, 1:30:29 PM] ---
[10/12/2016, 1:30:29 PM] Loading 1 platforms...
[10/12/2016, 1:30:29 PM] [My FritzBox] Initializing Fritz!Box platform...
[10/12/2016, 1:30:29 PM] [My FritzBox] Discovering accessories
[10/12/2016, 1:30:30 PM] [My FritzBox] Fritz!Box platform login successful
[10/12/2016, 1:30:31 PM] [My FritzBox] Outlets found: 087610162179,087610164200,C2:B6:94-900
[10/12/2016, 1:30:31 PM] [My FritzBox] Thermostats found:
[10/12/2016, 1:30:31 PM] [My FritzBox] Sensors found:
[10/12/2016, 1:30:31 PM] [My FritzBox] Initializing platform accessory 'Guest WLAN'...
[10/12/2016, 1:30:31 PM] [My FritzBox] Initializing platform accessory 'Highboard'...
[10/12/2016, 1:30:31 PM] [My FritzBox] Initializing platform accessory 'Vitrine'...
[10/12/2016, 1:30:31 PM] [My FritzBox] Initializing platform accessory 'C2:B6:94-900'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ xxx-xx-xx
    └────────────┘

[10/12/2016, 1:30:31 PM] Homebridge is running on port 51826.
[10/12/2016, 1:31:29 PM] [My FritzBox] Updating guest WLAN
[10/12/2016, 1:31:31 PM] [My FritzBox] Updating outlet 087610162179
[10/12/2016, 1:31:31 PM] [My FritzBox] Updating outlet 087610164200
[10/12/2016, 1:31:31 PM] [My FritzBox] Updating outlet C2:B6:94-900
TEST 087610162179
TEST 087610164200
[10/12/2016, 1:31:37 PM] [My FritzBox] > getTemperature failed - retrying in 3 seconds
[10/12/2016, 1:31:37 PM] [My FritzBox] { error: null,
  response:
   IncomingMessage {
     _readableState:
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _events:
      { end: [Object],
        close: [Object],
        data: [Function],
        error: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     socket:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'fritz.box',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        _bytesDispatched: 151,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     connection:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'fritz.box',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        _bytesDispatched: 151,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers:
      { connection: 'close',
        'content-length': '0',
        'content-type': 'text/plain; charset=utf-8' },
     rawHeaders:
      [ 'Connection',
        'close',
        'Content-Length',
        '0',
        'Content-Type',
        'text/plain; charset=utf-8' ],
     trailers: {},
     rawTrailers: [],
     upgrade: false,
     url: '',
     method: null,
     statusCode: 400,
     statusMessage: 'Bad Request',
     client:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'fritz.box',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        _bytesDispatched: 151,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     _consuming: true,
     _dumped: false,
     req:
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedHeader: {},
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET /webservices/homeautoswitch.lua?0=0&sid=d0ce15d029f86021&switchcmd=gettemperature&ain=087610162179 HTTP/1.1\r\nhost: fritz.box\r\nConnection: close\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        method: 'GET',
        path: '/webservices/homeautoswitch.lua?0=0&sid=d0ce15d029f86021&switchcmd=gettemperature&ain=087610162179',
        _ended: true,
        parser: null,
        res: [Circular] },
     request:
      Request {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        strictSSL: false,
        deviceList: [Object],
        callback: [Function],
        readable: true,
        writable: true,
        _qs: [Object],
        _auth: [Object],
        _oauth: [Object],
        _multipart: [Object],
        _redirect: [Object],
        _tunnel: [Object],
        headers: {},
        setHeader: [Function],
        hasHeader: [Function],
        getHeader: [Function],
        removeHeader: [Function],
        method: 'GET',
        localAddress: undefined,
        pool: [Object],
        dests: [],
        __isRequestRequest: true,
        _callback: [Function],
        uri: [Object],
        rejectUnauthorized: false,
        proxy: null,
        tunnel: false,
        setHost: true,
        originalCookieHeader: undefined,
        _disableCookies: true,
        _jar: undefined,
        port: 80,
        host: 'fritz.box',
        path: '/webservices/homeautoswitch.lua?0=0&sid=d0ce15d029f86021&switchcmd=gettemperature&ain=087610162179',
        httpModule: [Object],
        agentClass: [Object],
        agent: [Object],
        _started: true,
        href: 'http://fritz.box/webservices/homeautoswitch.lua?0=0&sid=d0ce15d029f86021&switchcmd=gettemperature&ain=087610162179',
        req: [Object],
        ntick: true,
        response: [Circular],
        originalHost: 'fritz.box',
        originalHostHeaderName: 'host',
        responseContent: [Circular],
        _ended: true,
        _callbackCalled: true },
     toJSON: [Function: responseToJSON],
     caseless: Caseless { dict: [Object] },
     read: [Function],
     body: '' },
  options:
   { url: 'http://fritz.box/webservices/homeautoswitch.lua?0=0&sid=d0ce15d029f86021&switchcmd=gettemperature&ain=087610162179',
     deviceList: [ [Object], [Object] ] } }
```

As you can see I added this just before line 383: `console.error('TEST '+self.ain);`. We can see the culprit AIN from the url in the error: it's 087610162179, which is one of the (normal) outlets. I still have no clue what is going on there; that outlet should work, right?

When I comment out the offending `getTemperature` call it runs without errors. I can't test the functionality at the moment though -- will do asap.

**Comment by andig** [comment]
> As you can see I added this just before line 383: console.error('TEST '+self.ain);. We can see the culprit AIN from the url in the error: it's 087610162179, which is one of the (normal) outlets. I still have no clue what is going on there; that outlet should work, right?

Thats strange. Can I (again) suggest to get access to your fb (u/p via email)? Will need to take a closer look :O

**Comment by rogiervandergeer** [comment]
So the switching of the group works fine, but getting the temperatures seems impossible. Also, switching the guest wlan doesn't work, but perhaps I should configure that first for it to work.

What do you need exactly to get access to? I'll see if I can provide that.

**Comment by andig** [comment]
> So the switching of the group works fine, but getting the temperatures seems impossible.

It is not possible but the code should already prevent this- that's where I'm confused. Please send user/ password/ url to cpuidle@gmx.de.

**Comment by andig** [comment]
As discussed: the error appears getting the temp from the switch, not the group. Please check with AVM what could be a root cause. This is really strange (and also separate from the intial problem).

**Comment by rogiervandergeer** [comment]
Exactly. Thanks for the help. I'll dive into the `getTemperature` problem myself. With respect to the groups, that is solved!

**Comment by andig** [comment]
Great, you're welcome! If there's anything to learn from the getTemp issue please let me know (or cc me in your mail to AVM ;)
